server:
  port: 8080

upload-path: F:/photo/

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_eims?serverTimezone=UTC&SuseUnicode=true&characterEncoding=UTF8
    username: root
    password: 
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${upload-path}


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

page:
  recruitment-limit: 1
  stu-recruitment-limit: 10
  apply-limit: 5
  enterprise-limit: 10
  sr-limit: 10

code:
